opt_in_rules:
  - closure_spacing
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace

type_body_length:
  warning: 300
  error: 400

identifier_name:
  excluded:
    - id
    - URL
    - kg
